### PR TITLE
Add public Encoding Templates schema

### PR DESCRIPTION
**Pull request by rohrlaf**
Will be available as https://raw.githubusercontent.com/bitmovin/bitmovin-api-sdk-examples/refs/heads/main/bitmovin-encoding-template.json to be added to the JSON Schema Store according to: https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to-add-a-json-schema-thats-self-hostedremoteexternal

Will be registered with:
```json
{
  "name": "Bitmovin Encoding Template",
  "description": "An encoding workflow from a single configuration template",
  "fileMatch": [
    "*.bitmovin.json",
    "*.bitmovin.yml",
    "*.bitmovin.yaml",
    "*.encoding.json",
    "*.encoding.yml",
    "*.encoding.yaml"
  ],
  "url": "https://raw.githubusercontent.com/bitmovin/bitmovin-api-sdk-examples/refs/heads/main/bitmovin-encoding-template.json"
}
```

### CODE REVIEW

**Comment by rohrlaf** [comment]
@moser4035 We could consider to host it on the Schema Store directly: https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to-add-a-json-schema-thats-hosted-in-this-repository

Anyways, we do have the fork now: https://github.com/bitmovin-engineering/schemastore/tree/feature/publish-encoding-template-schema (But I am unsure of how fast we can get updates through the review process, as it is a external dependency)

**Review by Knoblauchpilze — COMMENTED** [review]
The [first link](https://raw.githubusercontent.com/bitmovin/bitmovin-api-sdk-examples/refs/heads/main/bitmovin-encoding-template.json) you put on the description does not seem to be available to me (I get a 404).
Also I can't see the file in github as it's too big. I'm not sure I can review this properly :see_no_evil:

**Comment by moser4035** [comment]
> The [first link](https://raw.githubusercontent.com/bitmovin/bitmovin-api-sdk-examples/refs/heads/main/bitmovin-encoding-template.json) you put on the description does not seem to be available to me (I get a 404). Also I can't see the file in github as it's too big. I'm not sure I can review this properly 🙈

This is because it is not yet merged to `main` :)

**Review by moser4035 — APPROVED** [review]
For me looks good :+1:

**Comment by moser4035** [comment]
> @moser4035 We could consider to host it on the Schema Store directly: https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to-add-a-json-schema-thats-hosted-in-this-repository
> 
> Anyways, we do have the fork now: https://github.com/bitmovin-engineering/schemastore/tree/feature/publish-encoding-template-schema (But I am unsure of how fast we can get updates through the review process, as it is a external dependency)

Are there any benefits hosting it directly there?
I'm not really sure :thinking: Especially because we need to do more frequent updates on this files :sweat_smile: 

Maye it's better to keep it on our repos :thinking:

**Review by EmirDelicR — APPROVED** [review]

**Comment by rohrlaf** [comment]
The JSON schema is available now: https://raw.githubusercontent.com/bitmovin/bitmovin-api-sdk-examples/refs/heads/main/bitmovin-encoding-template.json

**Pull request merged**
